version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=ElasticSearch123*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=ElasticSearch123*
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elastic-net

volumes:
  elasticsearch-data:

networks:
  elastic-net:
    driver: bridge
