version: '3.8'

services:
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=ElasticSearch123*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=ElasticSearch123*
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elastic-net

  # MONGODB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_root
      - MONGO_INITDB_ROOT_PASSWORD=Mongo123*
    volumes:
      - mongodb-data:/data/db
    networks:
      - elastic-net
    ports:
      - '37017:27017'
  # Redis
  redis-stack:
    image: redis/redis-stack-server:latest # Sử dụng Redis Stack image mới nhất
    container_name: redis-stack
    ports:
      - '6379:6379' # Port Redis
      - '8001:8001' # Port RedisInsight
    volumes:
      - redis-data:/data # Lưu trữ dữ liệu Redis

volumes:
  elasticsearch-data:
    driver: local # Tùy chọn loại volume (local, volume,...) hoặc tùy chỉnh tùy theo cấu hình của bạn.
  mongodb-data:
    driver: local
  redis-data:
    driver: local

networks:
  elastic-net:
    driver: bridge
