openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
  description: Documentation for your API
servers:
  - url: http://localhost:3000
tags:
  - name: Permission Roles
    description: Endpoints related to permission roles
  - name: User Management
    description: Endpoints related to user './paths/user-management.yaml
components:
  schemas:
paths:
